image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade && 
    flutter update-packages --force-upgrade &&
    flutter run -d web-server --no-resident # prebuilds the app
  command: >
    flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
ports:
- port: 8080
  onOpen: open-preview
vscode:
  extensions:
    - dart-code.dart-code@3.20.1:gKwMOzlkrgxrb7aPrMdQ8w==
    - dart-code.flutter@3.20.0:fCUgJ2byoDmsmQf0Dq12+g==
    - vscodevim.vim@1.18.9:G9iVDLLWD41iBwKmpDTo1Q==